INSERT INTO USER(USER_ID, USER_EMAIL, USER_FIRST_NAME, USER_LAST_NAME, USER_JOB, USER_BIRTH_DAY) VALUES(1, 'Pavel_B@web.com', 'p', 'bachyla', 'Junior Software Engineer', '1990-05-10');
INSERT INTO USER(USER_ID, USER_EMAIL, USER_FIRST_NAME, USER_LAST_NAME, USER_JOB, USER_BIRTH_DAY) VALUES(2, 'Stanislau_K@tut.com', 'Stas', 'Kolodyuk', 'Senior Software Engineer', '1980-02-22');
INSERT INTO USER(USER_ID, USER_EMAIL, USER_FIRST_NAME, USER_LAST_NAME, USER_JOB, USER_BIRTH_DAY) VALUES(3, 'h2_database@tut.com', 'gran', 'dinj', 'H2 Contributor', '1987-01-03');
INSERT INTO USER(USER_ID, USER_EMAIL, USER_FIRST_NAME, USER_LAST_NAME, USER_JOB, USER_BIRTH_DAY) VALUES(4, 'Joe_Sanders@example.com', 'Joe', 'Sanders', 'Student', '1999-12-20');
INSERT INTO USER(USER_ID, USER_EMAIL, USER_FIRST_NAME, USER_LAST_NAME, USER_JOB, USER_BIRTH_DAY) VALUES(5, 'Ann_Burnes@url.com', 'Ann', 'Burnes', 'Team Leader', '1984-04-13');
INSERT INTO USER(USER_ID, USER_EMAIL, USER_FIRST_NAME, USER_LAST_NAME, USER_JOB, USER_BIRTH_DAY) VALUES(6, 'nagibator95@sample.com', 'Peter', 'Anderson', 'Student', '1978-08-06');
